#Minimal config
bind_to_address "127.0.0.1"
port "6605"

music_directory    "~/Music/"
playlist_directory "~/Music/Playlists/"
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

# Audio output block (choose based on your sound system)
audio_output {
    type "pipewire"
    name "MPD PipeWire Output"
}

# Symbolic links behavior
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"
