# Add support to custom app launch
windowrule = float, class:yazi
windowrule = center, class:yazi
windowrule = size 70% 80%, class:yazi

windowrule = float, class:rmpc
windowrule = center, class:rmpc
windowrule = size 65% 65%, class:rmpc
