# Add support to custom app launch windowrule
windowrule = float, class:yazi
windowrule = center, class:yazi
windowrule = size 1800 900, class:yazi

windowrule = float, class:rmpc
windowrule = center, class:rmpc
windowrule = size 1400 700, class:rmpc
