# Add support to custom app launch

windowrule = tag +rmpc, class:rmpc
windowrule = float, tag:rmpc
windowrule = size 65% 65%, tag:rmpc

layerrule = blur, walker
layerrule = ignorezero, walker
layerrule = ignorealpha 0.4, walker
