# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$terminalv2 = setsid uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, Yazi file manager, exec, $terminalv2 --app-id=yazi -e yazi "$@"
bindd = SUPER SHIFT, B, Chromium browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Bluetooth manager, exec, $terminalv2 --app-id=bluetui -e bluetui "$@"
bindd = SUPER SHIFT, Z, Zen browser, exec, uwsm-app -- zen-browser # Zen browser
bindd = SUPER SHIFT, M, Music player, exec, $terminalv2 --app-id=rmpc -e rmpc "$@"
bindd = SUPER SHIFT ALT, N, Network manager, exec, omarchy-launch-wifi
bindd = SUPER SHIFT, L, LazyVim editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT ALT, T, Activity monitor, exec, $terminal -e btop
bindd = SUPER SHIFT, T, Telegram, exec, Telegram # Telegram desktop
bindd = SUPER SHIFT ALT, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, S, Signal, exec, omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT ALT, G, Lazygit, exec, $terminal -e lazygit
bindd = SUPER SHIFT ALT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"c
#bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, C, Citate mendeley, exec, omarchy-launch-webapp "https://www.mendeley.com/reference-manager/library/all-references"
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-webapp "https://discord.com/channels/@me"
bindd = SUPER SHIFT, E, Gmail, exec, omarchy-launch-webapp "https://mail.google.com/mail/"
bindd = SUPER SHIFT, G, Github, exec, omarchy-launch-webapp "https://github.com/"
bindd = SUPER SHIFT, N, Notion, exec, omarchy-launch-webapp "https://www.notion.so/"
bindd = SUPER SHIFT, O, Onedrive, exec, omarchy-launch-webapp "https://uiiacid-my.sharepoint.com/"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, W, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT ALT, W, Word 365, exec, omarchy-launch-webapp "https://word.cloud.microsoft/?wdOrigin=DOCUMENTS.SHELL"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
