# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 3
    gaps_out = 3
    border_size = 2
    resize_on_border = true
    hover_icon_on_border = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 12
    dim_modal = true
    dim_inactive = true
    dim_strength = 0.125
    
    blur { #with risk battery drained
      enabled = true
      size = 9
      passes = 3
      ignore_opacity = true
      new_optimizations = true
      popups = true
      popups_ignorealpha = 0.4
    }

    bezier = overshoot, 0.06, 0.9, 0.1, 1.1
    animation = windows, 1, 4, default, popin 80%
    animation = workspaces, 1, 4, default
    animation = fade, 2
}

misc { #help to save battery power
    vfr = true
}
