# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = 4
    border_size = 2
    resize_on_border = true
    hover_icon_on_border = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 8
    dim_modal = true
    dim_inactive = true
    dim_strength = 0.125
    
    blur { #with risk battery drained
      enabled = true
      size = 5
      passes = 5
      ignore_opacity = true
      new_optimizations = true
      popups = true
      popups_ignorealpha = 0.4
    }

    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    animation = windowsIn, 1, 4, easeOutCirc, slide
    animation = windowsOut, 1, 4, easeOutCirc, slide
    animation = workspaces, 1, 4, easeOutCirc, slidefade 80%
    animation = fade, 1, 4, default
}

misc { #help to save battery power
    vfr = true
}
