# remove opacity
windowrule = opacity 1.0 1.0, class:^(jetbrains-phpstorm|jetbrains-idea|jetbrains-pycharm)

# tab & sidebar menus dragging
windowrulev2 = tag +jb, class:^jetbrains-.+$,floating:1
windowrulev2 = noinitialfocus, tag:jb

