#!/usr/bin/env sh

# Stored temporary data
TMP_DIR="/tmp/rmpc"

# Ensure directory was created
mkdir -p "$TMP_DIR"

# Stored album art
ALBUM_ART_PATH="$TMP_DIR/notification_cover"

# Path to fallback album art if no album art was found
DEFAULT_ALBUM_ART_PATH="$TMP_DIR/default_album_art.jpg"

# Save album art of the current playing song to a file
if ! rmpc albumart --output "$ALBUM_ART_PART"; then
  # Use default if rmpc returns non-zero exit code
  ALBUM_ART_PART="${DEFAULT_ALBUM_ART_PATH}"
fi

# Send notification
notify-send -i "${ALBUM_ART_PATH}" "Now Playing" "$ARTIST - $TITLE"

