[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "mime"
name = "*"  # use `url` if you're using the nightly version of Yazi
run  = "mime-ext"
prio = "high"

[plugin]
prepend_previewers = [
    { mime = "audio/*",   run = "exifaudio"}
]

# disable all preset of previewers
#preloaders = []
#previewers = []
