# Directories
alias c='clear && ls'
alias ca='clear'
alias ct='lta'

# working with dev tools
alias ld='lazydocker'
alias lg='lazygit'
alias gb='gobang'

# support for qt-wayland
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export XDG_SESSION_TYPE=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_STYLE_OVERRIDE=kvantum

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd

# clock-tui
alias ts='tclock -s 2 stopwatch'
alias tt='tclock -s 2 clock'

# bashrc
alias rb='source ~/.bashrc'

# activate python project
alias sa='source ~/PycharmProjects/RP-CDiL/.venv/bin/activate'

# move to thesis project
alias tp='cd ~/PycharmProjects/RP-CDiL/'

# uv path
. "$HOME/.local/share/../bin/env"

# intelli shell
eval "$(intelli-shell init bash)"
